# Algorithm Parameters
wall_distance: 0.15
front_turn_distance: 0.2
wall_track_distance: 0.4
angle_error_range: [-0.15, 0.15]
distance_error_range: [-0.15, 0.15]
front_angle_range: [335, 25]
left_angle_range: [90, 90]
left_front_angle_range: [80, 80]
left_back_angle_range: [100, 100]

# Hardware Parameters
max_linear_velocity: 0.22
max_angular_velocity: 2.84
max_scan_range: 3.5
